services:
  - type: web
    name: kanban-backend
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: node dist/main
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DB_HOST
        fromDatabase:
          name: kanban-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kanban-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: kanban-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kanban-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: kanban-db
          property: database

  - type: postgres
    name: kanban-db
    plan: free
    databaseName: kanban
    postgresMajorVersion: 16
